apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
  labels:
    app: storage
    tier: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage
      tier: stable
  template:
    metadata:
      labels:
        app: storage
        tier: stable
    spec:
      containers:
      - name: storage
        image: gcr.io/petomalina/storage
        ports:
        - containerPort: 80